<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
class CountrySeeder extends Seeder
{
     /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        DB::table('countries')->truncate();
       
        $now = Carbon::now();

        $countries = [
            ['id' => 2, 'country_name' => 'Afghanistan', 'country_short_code' => 'AF', 'is_active' => 1],
            ['id' => 3, 'country_name' => 'Albania', 'country_short_code' => 'AL', 'is_active' => 1],
            ['id' => 4, 'country_name' => 'Algeria', 'country_short_code' => 'DZ', 'is_active' => 1],
            ['id' => 5, 'country_name' => 'American Samoa', 'country_short_code' => 'AS', 'is_active' => 1],
            ['id' => 6, 'country_name' => 'Andorra', 'country_short_code' => 'AD', 'is_active' => 1],
            ['id' => 7, 'country_name' => 'Angola', 'country_short_code' => 'AO', 'is_active' => 1],
            ['id' => 8, 'country_name' => 'Anguilla', 'country_short_code' => 'AI', 'is_active' => 1],
            ['id' => 9, 'country_name' => 'Antarctica', 'country_short_code' => 'AQ', 'is_active' => 1],
            ['id' => 10, 'country_name' => 'Antigua and Barbuda', 'country_short_code' => 'AG', 'is_active' => 1],
            ['id' => 11, 'country_name' => 'Argentina', 'country_short_code' => 'AR', 'is_active' => 1],
            ['id' => 12, 'country_name' => 'Armenia', 'country_short_code' => 'AM', 'is_active' => 1],
            ['id' => 13, 'country_name' => 'Aruba', 'country_short_code' => 'AW', 'is_active' => 1],
            ['id' => 14, 'country_name' => 'Australia', 'country_short_code' => 'AU', 'is_active' => 1],
            ['id' => 15, 'country_name' => 'Austria', 'country_short_code' => 'AT', 'is_active' => 1],
            ['id' => 16, 'country_name' => 'Azerbaijan', 'country_short_code' => 'AZ', 'is_active' => 1],
            ['id' => 17, 'country_name' => 'Bahamas (the)', 'country_short_code' => 'BS', 'is_active' => 1],
            ['id' => 18, 'country_name' => 'Bahrain', 'country_short_code' => 'BH', 'is_active' => 1],
            ['id' => 19, 'country_name' => 'Bangladesh', 'country_short_code' => 'BD', 'is_active' => 1],
            ['id' => 20, 'country_name' => 'Barbados', 'country_short_code' => 'BB', 'is_active' => 1],
            ['id' => 21, 'country_name' => 'Belarus', 'country_short_code' => 'BY', 'is_active' => 1],
            ['id' => 22, 'country_name' => 'Belgium', 'country_short_code' => 'BE', 'is_active' => 1],
            ['id' => 23, 'country_name' => 'Belize', 'country_short_code' => 'BZ', 'is_active' => 1],
            ['id' => 24, 'country_name' => 'Benin', 'country_short_code' => 'BJ', 'is_active' => 1],
            ['id' => 25, 'country_name' => 'Bermuda', 'country_short_code' => 'BM', 'is_active' => 1],
            ['id' => 26, 'country_name' => 'Bhutan', 'country_short_code' => 'BT', 'is_active' => 1],
            ['id' => 27, 'country_name' => 'Bolivia (Plurinational State of)', 'country_short_code' => 'BO', 'is_active' => 1],
            ['id' => 28, 'country_name' => 'Bonaire, Sint Eustatius and Saba', 'country_short_code' => 'BQ', 'is_active' => 1],
            ['id' => 29, 'country_name' => 'Bosnia and Herzegovina', 'country_short_code' => 'BA', 'is_active' => 1],
            ['id' => 30, 'country_name' => 'Botswana', 'country_short_code' => 'BW', 'is_active' => 1],
            ['id' => 31, 'country_name' => 'Bouvet Island', 'country_short_code' => 'BV', 'is_active' => 1],
            ['id' => 32, 'country_name' => 'Brazil', 'country_short_code' => 'BR', 'is_active' => 1],
            ['id' => 33, 'country_name' => 'British Indian Ocean Territory (the)', 'country_short_code' => 'IO', 'is_active' => 1],
            ['id' => 34, 'country_name' => 'Brunei Darussalam', 'country_short_code' => 'BN', 'is_active' => 1],
            ['id' => 35, 'country_name' => 'Bulgaria', 'country_short_code' => 'BG', 'is_active' => 1],
            ['id' => 36, 'country_name' => 'Burkina Faso', 'country_short_code' => 'BF', 'is_active' => 1],
            ['id' => 37, 'country_name' => 'Burundi', 'country_short_code' => 'BI', 'is_active' => 1],
            ['id' => 38, 'country_name' => 'Cabo Verde', 'country_short_code' => 'CV', 'is_active' => 1],
            ['id' => 39, 'country_name' => 'Cambodia', 'country_short_code' => 'KH', 'is_active' => 1],
            ['id' => 40, 'country_name' => 'Cameroon', 'country_short_code' => 'CM', 'is_active' => 1],
            ['id' => 41, 'country_name' => 'Canada', 'country_short_code' => 'CA', 'is_active' => 1],
            ['id' => 42, 'country_name' => 'Cayman Islands (the)', 'country_short_code' => 'KY', 'is_active' => 1],
            ['id' => 43, 'country_name' => 'Central African Republic (the)', 'country_short_code' => 'CF', 'is_active' => 1],
            ['id' => 44, 'country_name' => 'Chad', 'country_short_code' => 'TD', 'is_active' => 1],
            ['id' => 45, 'country_name' => 'Chile', 'country_short_code' => 'CL', 'is_active' => 1],
            ['id' => 46, 'country_name' => 'China', 'country_short_code' => 'CN', 'is_active' => 1],
            ['id' => 47, 'country_name' => 'Christmas Island', 'country_short_code' => 'CX', 'is_active' => 1],
            ['id' => 48, 'country_name' => 'Cocos (Keeling) Islands (the)', 'country_short_code' => 'CC', 'is_active' => 1],
            ['id' => 49, 'country_name' => 'Colombia', 'country_short_code' => 'CO', 'is_active' => 1],
            ['id' => 50, 'country_name' => 'Comoros (the)', 'country_short_code' => 'KM', 'is_active' => 1],
            ['id' => 51, 'country_name' => 'Congo (the Democratic Republic of the)', 'country_short_code' => 'CD', 'is_active' => 1],
            ['id' => 52, 'country_name' => 'Congo (the)', 'country_short_code' => 'CG', 'is_active' => 1],
            ['id' => 53, 'country_name' => 'Cook Islands (the)', 'country_short_code' => 'CK', 'is_active' => 1],
            ['id' => 54, 'country_name' => 'Costa Rica', 'country_short_code' => 'CR', 'is_active' => 1],
            ['id' => 55, 'country_name' => 'Croatia', 'country_short_code' => 'HR', 'is_active' => 1],
            ['id' => 56, 'country_name' => 'Cuba', 'country_short_code' => 'CU', 'is_active' => 1],
            ['id' => 57, 'country_name' => 'Curaçao', 'country_short_code' => 'CW', 'is_active' => 1],
            ['id' => 58, 'country_name' => 'Cyprus', 'country_short_code' => 'CY', 'is_active' => 1],
            ['id' => 59, 'country_name' => 'Czechia', 'country_short_code' => 'CZ', 'is_active' => 1],
            ['id' => 60, 'country_name' => 'Côte d\'Ivoire', 'country_short_code' => 'CI', 'is_active' => 1],
            ['id' => 61, 'country_name' => 'Denmark', 'country_short_code' => 'DK', 'is_active' => 1],
            ['id' => 62, 'country_name' => 'Djibouti', 'country_short_code' => 'DJ', 'is_active' => 1],
            ['id' => 63, 'country_name' => 'Dominica', 'country_short_code' => 'DM', 'is_active' => 1],
            ['id' => 64, 'country_name' => 'Dominican Republic (the)', 'country_short_code' => 'DO', 'is_active' => 1],
            ['id' => 65, 'country_name' => 'Ecuador', 'country_short_code' => 'EC', 'is_active' => 1],
            ['id' => 66, 'country_name' => 'Egypt', 'country_short_code' => 'EG', 'is_active' => 1],
            ['id' => 67, 'country_name' => 'El Salvador', 'country_short_code' => 'SV', 'is_active' => 1],
            ['id' => 68, 'country_name' => 'Equatorial Guinea', 'country_short_code' => 'GQ', 'is_active' => 1],
            ['id' => 69, 'country_name' => 'Eritrea', 'country_short_code' => 'ER', 'is_active' => 1],
            ['id' => 70, 'country_name' => 'Estonia', 'country_short_code' => 'EE', 'is_active' => 1],
            ['id' => 71, 'country_name' => 'Eswatini', 'country_short_code' => 'SZ', 'is_active' => 1],
            ['id' => 72, 'country_name' => 'Ethiopia', 'country_short_code' => 'ET', 'is_active' => 1],
            ['id' => 73, 'country_name' => 'Falkland Islands (the) [Malvinas]', 'country_short_code' => 'FK', 'is_active' => 1],
            ['id' => 74, 'country_name' => 'Faroe Islands (the)', 'country_short_code' => 'FO', 'is_active' => 1],
            ['id' => 75, 'country_name' => 'Fiji', 'country_short_code' => 'FJ', 'is_active' => 1],
            ['id' => 76, 'country_name' => 'Finland', 'country_short_code' => 'FI', 'is_active' => 1],
            ['id' => 77, 'country_name' => 'France', 'country_short_code' => 'FR', 'is_active' => 1],
            ['id' => 78, 'country_name' => 'French Guiana', 'country_short_code' => 'GF', 'is_active' => 1],
            ['id' => 79, 'country_name' => 'French Polynesia', 'country_short_code' => 'PF', 'is_active' => 1],
            ['id' => 80, 'country_name' => 'French Southern Territories (the)', 'country_short_code' => 'TF', 'is_active' => 1],
            ['id' => 81, 'country_name' => 'Gabon', 'country_short_code' => 'GA', 'is_active' => 1],
            ['id' => 82, 'country_name' => 'Gambia (the)', 'country_short_code' => 'GM', 'is_active' => 1],
            ['id' => 83, 'country_name' => 'Georgia', 'country_short_code' => 'GE', 'is_active' => 1],
            ['id' => 84, 'country_name' => 'Germany', 'country_short_code' => 'DE', 'is_active' => 1],
            ['id' => 85, 'country_name' => 'Ghana', 'country_short_code' => 'GH', 'is_active' => 1],
            ['id' => 86, 'country_name' => 'Gibraltar', 'country_short_code' => 'GI', 'is_active' => 1],
            ['id' => 87, 'country_name' => 'Greece', 'country_short_code' => 'GR', 'is_active' => 1],
            ['id' => 88, 'country_name' => 'Greenland', 'country_short_code' => 'GL', 'is_active' => 1],
            ['id' => 89, 'country_name' => 'Grenada', 'country_short_code' => 'GD', 'is_active' => 1],
            ['id' => 90, 'country_name' => 'Guadeloupe', 'country_short_code' => 'GP', 'is_active' => 1],
            ['id' => 91, 'country_name' => 'Guam', 'country_short_code' => 'GU', 'is_active' => 1],
            ['id' => 92, 'country_name' => 'Guatemala', 'country_short_code' => 'GT', 'is_active' => 1],
            ['id' => 93, 'country_name' => 'Guernsey', 'country_short_code' => 'GG', 'is_active' => 1],
            ['id' => 94, 'country_name' => 'Guinea', 'country_short_code' => 'GN', 'is_active' => 1],
            ['id' => 95, 'country_name' => 'Guinea-Bissau', 'country_short_code' => 'GW', 'is_active' => 1],
            ['id' => 96, 'country_name' => 'Guyana', 'country_short_code' => 'GY', 'is_active' => 1],
            ['id' => 97, 'country_name' => 'Haiti', 'country_short_code' => 'HT', 'is_active' => 1],
            ['id' => 98, 'country_name' => 'Heard Island and McDonald Islands', 'country_short_code' => 'HM', 'is_active' => 1],
            ['id' => 99, 'country_name' => 'Holy See (the)', 'country_short_code' => 'VA', 'is_active' => 1],
            ['id' => 100, 'country_name' => 'Honduras', 'country_short_code' => 'HN', 'is_active' => 1],
            ['id' => 101, 'country_name' => 'Hong Kong', 'country_short_code' => 'HK', 'is_active' => 1],
            ['id' => 102, 'country_name' => 'Hungary', 'country_short_code' => 'HU', 'is_active' => 1],
            ['id' => 103, 'country_name' => 'Iceland', 'country_short_code' => 'IS', 'is_active' => 1],
            ['id' => 104, 'country_name' => 'India', 'country_short_code' => 'IN', 'is_active' => 1],
            ['id' => 105, 'country_name' => 'Indonesia', 'country_short_code' => 'ID', 'is_active' => 1],
            ['id' => 106, 'country_name' => 'Iran (Islamic Republic of)', 'country_short_code' => 'IR', 'is_active' => 1],
            ['id' => 107, 'country_name' => 'Iraq', 'country_short_code' => 'IQ', 'is_active' => 1],
            ['id' => 108, 'country_name' => 'Ireland', 'country_short_code' => 'IE', 'is_active' => 1],
            ['id' => 109, 'country_name' => 'Isle of Man', 'country_short_code' => 'IM', 'is_active' => 1],
            ['id' => 110, 'country_name' => 'Israel', 'country_short_code' => 'IL', 'is_active' => 1],
            ['id' => 111, 'country_name' => 'Italy', 'country_short_code' => 'IT', 'is_active' => 1],
            ['id' => 112, 'country_name' => 'Jamaica', 'country_short_code' => 'JM', 'is_active' => 1],
            ['id' => 113, 'country_name' => 'Japan', 'country_short_code' => 'JP', 'is_active' => 1],
            ['id' => 114, 'country_name' => 'Jersey', 'country_short_code' => 'JE', 'is_active' => 1],
            ['id' => 115, 'country_name' => 'Jordan', 'country_short_code' => 'JO', 'is_active' => 1],
            ['id' => 116, 'country_name' => 'Kazakhstan', 'country_short_code' => 'KZ', 'is_active' => 1],
            ['id' => 117, 'country_name' => 'Kenya', 'country_short_code' => 'KE', 'is_active' => 1],
            ['id' => 118, 'country_name' => 'Kiribati', 'country_short_code' => 'KI', 'is_active' => 1],
            ['id' => 119, 'country_name' => 'Korea (the Democratic People\'s Republic of)', 'country_short_code' => 'KP', 'is_active' => 1],
            ['id' => 120, 'country_name' => 'Korea (the Republic of)', 'country_short_code' => 'KR', 'is_active' => 1],
            ['id' => 121, 'country_name' => 'Kuwait', 'country_short_code' => 'KW', 'is_active' => 1],
            ['id' => 122, 'country_name' => 'Kyrgyzstan', 'country_short_code' => 'KG', 'is_active' => 1],
            ['id' => 123, 'country_name' => 'Lao People\'s Democratic Republic (the)', 'country_short_code' => 'LA', 'is_active' => 1],
            ['id' => 124, 'country_name' => 'Latvia', 'country_short_code' => 'LV', 'is_active' => 1],
            ['id' => 125, 'country_name' => 'Lebanon', 'country_short_code' => 'LB', 'is_active' => 1],
            ['id' => 126, 'country_name' => 'Lesotho', 'country_short_code' => 'LS', 'is_active' => 1],
            ['id' => 127, 'country_name' => 'Liberia', 'country_short_code' => 'LR', 'is_active' => 1],
            ['id' => 128, 'country_name' => 'Libya', 'country_short_code' => 'LY', 'is_active' => 1],
            ['id' => 129, 'country_name' => 'Liechtenstein', 'country_short_code' => 'LI', 'is_active' => 1],
            ['id' => 130, 'country_name' => 'Lithuania', 'country_short_code' => 'LT', 'is_active' => 1],
            ['id' => 131, 'country_name' => 'Luxembourg', 'country_short_code' => 'LU', 'is_active' => 1],
            ['id' => 132, 'country_name' => 'Macao', 'country_short_code' => 'MO', 'is_active' => 1],
            ['id' => 133, 'country_name' => 'Madagascar', 'country_short_code' => 'MG', 'is_active' => 1],
            ['id' => 134, 'country_name' => 'Malawi', 'country_short_code' => 'MW', 'is_active' => 1],
            ['id' => 135, 'country_name' => 'Malaysia', 'country_short_code' => 'MY', 'is_active' => 1],
            ['id' => 136, 'country_name' => 'Maldives', 'country_short_code' => 'MV', 'is_active' => 1],
            ['id' => 137, 'country_name' => 'Mali', 'country_short_code' => 'ML', 'is_active' => 1],
            ['id' => 138, 'country_name' => 'Malta', 'country_short_code' => 'MT', 'is_active' => 1],
            ['id' => 139, 'country_name' => 'Marshall Islands (the)', 'country_short_code' => 'MH', 'is_active' => 1],
            ['id' => 140, 'country_name' => 'Martinique', 'country_short_code' => 'MQ', 'is_active' => 1],
            ['id' => 141, 'country_name' => 'Mauritania', 'country_short_code' => 'MR', 'is_active' => 1],
            ['id' => 142, 'country_name' => 'Mauritius', 'country_short_code' => 'MU', 'is_active' => 1],
            ['id' => 143, 'country_name' => 'Mayotte', 'country_short_code' => 'YT', 'is_active' => 1],
            ['id' => 144, 'country_name' => 'Mexico', 'country_short_code' => 'MX', 'is_active' => 1],
            ['id' => 145, 'country_name' => 'Micronesia (Federated States of)', 'country_short_code' => 'FM', 'is_active' => 1],
            ['id' => 146, 'country_name' => 'Moldova (the Republic of)', 'country_short_code' => 'MD', 'is_active' => 1],
            ['id' => 147, 'country_name' => 'Monaco', 'country_short_code' => 'MC', 'is_active' => 1],
            ['id' => 148, 'country_name' => 'Mongolia', 'country_short_code' => 'MN', 'is_active' => 1],
            ['id' => 149, 'country_name' => 'Montenegro', 'country_short_code' => 'ME', 'is_active' => 1],
            ['id' => 150, 'country_name' => 'Montserrat', 'country_short_code' => 'MS', 'is_active' => 1],
            ['id' => 151, 'country_name' => 'Morocco', 'country_short_code' => 'MA', 'is_active' => 1],
            ['id' => 152, 'country_name' => 'Mozambique', 'country_short_code' => 'MZ', 'is_active' => 1],
            ['id' => 153, 'country_name' => 'Myanmar', 'country_short_code' => 'MM', 'is_active' => 1],
            ['id' => 154, 'country_name' => 'Namibia', 'country_short_code' => 'NA', 'is_active' => 1],
            ['id' => 155, 'country_name' => 'Nauru', 'country_short_code' => 'NR', 'is_active' => 1],
            ['id' => 156, 'country_name' => 'Nepal', 'country_short_code' => 'NP', 'is_active' => 1],
            ['id' => 157, 'country_name' => 'Netherlands (the)', 'country_short_code' => 'NL', 'is_active' => 1],
            ['id' => 158, 'country_name' => 'New Caledonia', 'country_short_code' => 'NC', 'is_active' => 1],
            ['id' => 159, 'country_name' => 'New Zealand', 'country_short_code' => 'NZ', 'is_active' => 1],
            ['id' => 160, 'country_name' => 'Nicaragua', 'country_short_code' => 'NI', 'is_active' => 1],
            ['id' => 161, 'country_name' => 'Niger (the)', 'country_short_code' => 'NE', 'is_active' => 1],
            ['id' => 162, 'country_name' => 'Nigeria', 'country_short_code' => 'NG', 'is_active' => 1],
            ['id' => 163, 'country_name' => 'Niue', 'country_short_code' => 'NU', 'is_active' => 1],
            ['id' => 164, 'country_name' => 'Norfolk Island', 'country_short_code' => 'NF', 'is_active' => 1],
            ['id' => 165, 'country_name' => 'Northern Mariana Islands (the)', 'country_short_code' => 'MP', 'is_active' => 1],
            ['id' => 166, 'country_name' => 'Norway', 'country_short_code' => 'NO', 'is_active' => 1],
            ['id' => 167, 'country_name' => 'Oman', 'country_short_code' => 'OM', 'is_active' => 1],
            ['id' => 168, 'country_name' => 'Pakistan', 'country_short_code' => 'PK', 'is_active' => 1],
            ['id' => 169, 'country_name' => 'Palau', 'country_short_code' => 'PW', 'is_active' => 1],
            ['id' => 170, 'country_name' => 'Palestine, State of', 'country_short_code' => 'PS', 'is_active' => 1],
            ['id' => 171, 'country_name' => 'Panama', 'country_short_code' => 'PA', 'is_active' => 1],
            ['id' => 172, 'country_name' => 'Papua New Guinea', 'country_short_code' => 'PG', 'is_active' => 1],
            ['id' => 173, 'country_name' => 'Paraguay', 'country_short_code' => 'PY', 'is_active' => 1],
            ['id' => 174, 'country_name' => 'Peru', 'country_short_code' => 'PE', 'is_active' => 1],
            ['id' => 175, 'country_name' => 'Philippines (the)', 'country_short_code' => 'PH', 'is_active' => 1],
            ['id' => 176, 'country_name' => 'Pitcairn', 'country_short_code' => 'PN', 'is_active' => 1],
            ['id' => 177, 'country_name' => 'Poland', 'country_short_code' => 'PL', 'is_active' => 1],
            ['id' => 178, 'country_name' => 'Portugal', 'country_short_code' => 'PT', 'is_active' => 1],
            ['id' => 179, 'country_name' => 'Puerto Rico', 'country_short_code' => 'PR', 'is_active' => 1],
            ['id' => 180, 'country_name' => 'Qatar', 'country_short_code' => 'QA', 'is_active' => 1],
            ['id' => 181, 'country_name' => 'Republic of North Macedonia', 'country_short_code' => 'MK', 'is_active' => 1],
            ['id' => 182, 'country_name' => 'Romania', 'country_short_code' => 'RO', 'is_active' => 1],
            ['id' => 183, 'country_name' => 'Russian Federation (the)', 'country_short_code' => 'RU', 'is_active' => 1],
            ['id' => 184, 'country_name' => 'Rwanda', 'country_short_code' => 'RW', 'is_active' => 1],
            ['id' => 185, 'country_name' => 'Réunion', 'country_short_code' => 'RE', 'is_active' => 1],
            ['id' => 186, 'country_name' => 'Saint Barthélemy', 'country_short_code' => 'BL', 'is_active' => 1],
            ['id' => 187, 'country_name' => 'Saint Helena, Ascension and Tristan da Cunha', 'country_short_code' => 'SH', 'is_active' => 1],
            ['id' => 188, 'country_name' => 'Saint Kitts and Nevis', 'country_short_code' => 'KN', 'is_active' => 1],
            ['id' => 189, 'country_name' => 'Saint Lucia', 'country_short_code' => 'LC', 'is_active' => 1],
            ['id' => 190, 'country_name' => 'Saint Martin (French part)', 'country_short_code' => 'MF', 'is_active' => 1],
            ['id' => 191, 'country_name' => 'Saint Pierre and Miquelon', 'country_short_code' => 'PM', 'is_active' => 1],
            ['id' => 192, 'country_name' => 'Saint Vincent and the Grenadines', 'country_short_code' => 'VC', 'is_active' => 1],
            ['id' => 193, 'country_name' => 'Samoa', 'country_short_code' => 'WS', 'is_active' => 1],
            ['id' => 194, 'country_name' => 'San Marino', 'country_short_code' => 'SM', 'is_active' => 1],
            ['id' => 195, 'country_name' => 'Sao Tome and Principe', 'country_short_code' => 'ST', 'is_active' => 1],
            ['id' => 196, 'country_name' => 'Saudi Arabia', 'country_short_code' => 'SA', 'is_active' => 1],
            ['id' => 197, 'country_name' => 'Senegal', 'country_short_code' => 'SN', 'is_active' => 1],
            ['id' => 198, 'country_name' => 'Serbia', 'country_short_code' => 'RS', 'is_active' => 1],
            ['id' => 199, 'country_name' => 'Seychelles', 'country_short_code' => 'SC', 'is_active' => 1],
            ['id' => 200, 'country_name' => 'Sierra Leone', 'country_short_code' => 'SL', 'is_active' => 1],
            ['id' => 201, 'country_name' => 'Singapore', 'country_short_code' => 'SG', 'is_active' => 1],
            ['id' => 202, 'country_name' => 'Sint Maarten (Dutch part)', 'country_short_code' => 'SX', 'is_active' => 1],
            ['id' => 203, 'country_name' => 'Slovakia', 'country_short_code' => 'SK', 'is_active' => 1],
            ['id' => 204, 'country_name' => 'Slovenia', 'country_short_code' => 'SI', 'is_active' => 1],
            ['id' => 205, 'country_name' => 'Solomon Islands', 'country_short_code' => 'SB', 'is_active' => 1],
            ['id' => 206, 'country_name' => 'Somalia', 'country_short_code' => 'SO', 'is_active' => 1],
            ['id' => 207, 'country_name' => 'South Africa', 'country_short_code' => 'ZA', 'is_active' => 1],
            ['id' => 208, 'country_name' => 'South Georgia and the South Sandwich Islands', 'country_short_code' => 'GS', 'is_active' => 1],
            ['id' => 209, 'country_name' => 'South Sudan', 'country_short_code' => 'SS', 'is_active' => 1],
            ['id' => 210, 'country_name' => 'Spain', 'country_short_code' => 'ES', 'is_active' => 1],
            ['id' => 211, 'country_name' => 'Sri Lanka', 'country_short_code' => 'LK', 'is_active' => 1],
            ['id' => 212, 'country_name' => 'Sudan (the)', 'country_short_code' => 'SD', 'is_active' => 1],
            ['id' => 213, 'country_name' => 'Suriname', 'country_short_code' => 'SR', 'is_active' => 1],
            ['id' => 214, 'country_name' => 'Svalbard and Jan Mayen', 'country_short_code' => 'SJ', 'is_active' => 1],
            ['id' => 215, 'country_name' => 'Sweden', 'country_short_code' => 'SE', 'is_active' => 1],
            ['id' => 216, 'country_name' => 'Switzerland', 'country_short_code' => 'CH', 'is_active' => 1],
            ['id' => 217, 'country_name' => 'Syrian Arab Republic', 'country_short_code' => 'SY', 'is_active' => 1],
            ['id' => 218, 'country_name' => 'Taiwan (Province of China)', 'country_short_code' => 'TW', 'is_active' => 1],
            ['id' => 219, 'country_name' => 'Tajikistan', 'country_short_code' => 'TJ', 'is_active' => 1],
            ['id' => 220, 'country_name' => 'Tanzania, United Republic of', 'country_short_code' => 'TZ', 'is_active' => 1],
            ['id' => 221, 'country_name' => 'Thailand', 'country_short_code' => 'TH', 'is_active' => 1],
            ['id' => 222, 'country_name' => 'Timor-Leste', 'country_short_code' => 'TL', 'is_active' => 1],
            ['id' => 223, 'country_name' => 'Togo', 'country_short_code' => 'TG', 'is_active' => 1],
            ['id' => 224, 'country_name' => 'Tokelau', 'country_short_code' => 'TK', 'is_active' => 1],
            ['id' => 225, 'country_name' => 'Tonga', 'country_short_code' => 'TO', 'is_active' => 1],
            ['id' => 226, 'country_name' => 'Trinidad and Tobago', 'country_short_code' => 'TT', 'is_active' => 1],
            ['id' => 227, 'country_name' => 'Tunisia', 'country_short_code' => 'TN', 'is_active' => 1],
            ['id' => 228, 'country_name' => 'Turkey', 'country_short_code' => 'TR', 'is_active' => 1],
            ['id' => 229, 'country_name' => 'Turkmenistan', 'country_short_code' => 'TM', 'is_active' => 1],
            ['id' => 230, 'country_name' => 'Turks and Caicos Islands (the)', 'country_short_code' => 'TC', 'is_active' => 1],
            ['id' => 231, 'country_name' => 'Tuvalu', 'country_short_code' => 'TV', 'is_active' => 1],
            ['id' => 232, 'country_name' => 'Uganda', 'country_short_code' => 'UG', 'is_active' => 1],
            ['id' => 233, 'country_name' => 'Ukraine', 'country_short_code' => 'UA', 'is_active' => 1],
            ['id' => 234, 'country_name' => 'United Arab Emirates (the)', 'country_short_code' => 'AE', 'is_active' => 1],
            ['id' => 235, 'country_name' => 'United Kingdom of Great Britain and Northern Ireland (the)', 'country_short_code' => 'GB', 'is_active' => 1],
            ['id' => 236, 'country_name' => 'United States Minor Outlying Islands (the)', 'country_short_code' => 'UM', 'is_active' => 1],
            ['id' => 237, 'country_name' => 'United States of America (the)', 'country_short_code' => 'US', 'is_active' => 1],
            ['id' => 238, 'country_name' => 'Uruguay', 'country_short_code' => 'UY', 'is_active' => 1],
            ['id' => 239, 'country_name' => 'Uzbekistan', 'country_short_code' => 'UZ', 'is_active' => 1],
            ['id' => 240, 'country_name' => 'Vanuatu', 'country_short_code' => 'VU', 'is_active' => 1],
            ['id' => 241, 'country_name' => 'Venezuela (Bolivarian Republic of)', 'country_short_code' => 'VE', 'is_active' => 1],
            ['id' => 242, 'country_name' => 'Viet Nam', 'country_short_code' => 'VN', 'is_active' => 1],
            ['id' => 243, 'country_name' => 'Virgin Islands (British)', 'country_short_code' => 'VG', 'is_active' => 1],
            ['id' => 244, 'country_name' => 'Virgin Islands (U.S.)', 'country_short_code' => 'VI', 'is_active' => 1],
            ['id' => 245, 'country_name' => 'Wallis and Futuna', 'country_short_code' => 'WF', 'is_active' => 1],
            ['id' => 246, 'country_name' => 'Western Sahara', 'country_short_code' => 'EH', 'is_active' => 1],
            ['id' => 247, 'country_name' => 'Yemen', 'country_short_code' => 'YE', 'is_active' => 1],
            ['id' => 248, 'country_name' => 'Zambia', 'country_short_code' => 'ZM', 'is_active' => 1],
            ['id' => 249, 'country_name' => 'Zimbabwe', 'country_short_code' => 'ZW', 'is_active' => 1],
            ['id' => 250, 'country_name' => 'Åland Islands', 'country_short_code' => 'AX', 'is_active' => 1],
        ];

        // Process each row to add timestamps
        $dataToInsert = array_map(function ($item) use ($now) {
            return array_merge($item, [
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }, $countries);

        // Insert in chunks of 100 to stay efficient and avoid query size limits
        foreach (array_chunk($dataToInsert, 100) as $chunk) {
            DB::table('countries')->insert($chunk);
        }
    }
}